# Automapper configuration
# [templates.example_template] - example_template should be replaced with the name of your map template.
# directory - The direct path to our map files.
# map_files - These are the names of the map files, including the extension, that will be loaded. Supports multiple for randomness.
# required_map - This is the name of the required map that needs to be loaded in order for this template to load.
# coordinates - The coordinates of the map template placement. (X, Y, Z). PLEASE NOTE: The Z coordinate is the same as would be shown in SDMM. NOT IN GAME.
# leave it at 1 if it is not a multi-z map. It is relative to the map file Z, not the one loaded in game.
# trait_name - The name of the Z level trait that will be used to determine what Z level we use.
# Traits - Station (for station relatied edits), CentCom (for edits on the CC map), Mining (for edits on Lavaland)
# More can be found in code\__DEFINES\maps.dm

# CENTRAL COMMAND MAP TEMPLATES
# CC Ferry Dock - Admin Shuttle
[templates.centcom_ferry_dock]
map_files = ["centcom_ferry_dock.dmm"]
directory = "_maps/skyrat/automapper/templates/centcom/"
required_map = "builtin"
coordinates = [128, 79, 1]
trait_name = "CentCom"

# CC Evac Docking Port Removal
[templates.centcom_shuttle_dock]
map_files = ["centcom_shuttle_dock.dmm"]
directory = "_maps/skyrat/automapper/templates/centcom/"
required_map = "builtin"
coordinates = [206, 85, 1]
trait_name = "CentCom"

# METASTATION MAP TEMPLATES
# Metastation Arrivals
[templates.metastaton_arrivals]
map_files = ["metastation_arrivals.dmm"]
directory = "_maps/skyrat/automapper/templates/metastation/"
required_map = "MetaStation.dmm"
coordinates = [20, 107, 1]
trait_name = "Station"

# Metastation Cryo
[templates.metastation_cryo]
map_files = ["metastation_cryo.dmm"]
directory = "_maps/skyrat/automapper/templates/metastation/"
required_map = "MetaStation.dmm"
coordinates = [133, 182, 1]
trait_name = "Station"

# Metastation Armory
[templates.metastation_armory]
map_files = ["metastation_armory.dmm"]
directory = "_maps/skyrat/automapper/templates/metastation/"
required_map = "MetaStation.dmm"
coordinates = [101, 170, 1]
trait_name = "Station"

# Metastation Supermatter Chamber
[templates.metastation_supermatter]
map_files = ["metastation_supermatter.dmm"]
directory = "_maps/skyrat/automapper/templates/metastation/"
required_map = "MetaStation.dmm"
coordinates = [163, 155, 1]
trait_name = "Station"

# ICEBOX MAP EDITS
# Icebox Arrivals
[templates.icebox_arrivals]
map_files = ["icebox_arrivals.dmm"]
directory = "_maps/skyrat/automapper/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [8, 115, 3]
trait_name = "Station"

# Icebox Armory Middle
[templates.icebox_armory_middle]
map_files = ["icebox_armory_middle.dmm"]
directory = "_maps/skyrat/automapper/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [104, 178, 2]
trait_name = "Station"

# Icebox Cryo
[templates.icebox_cryo]
map_files = ["icebox_cryo.dmm"]
directory = "_maps/skyrat/automapper/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [117, 142, 3]
trait_name = "Station"

# Icebox HoP Maint
[templates.icebox_hop_maint]
map_files = ["icebox_hop_maint.dmm"]
directory = "_maps/skyrat/automapper/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [98, 123, 3]
trait_name = "Station"

# Icebox Supermatter Chamber
[templates.icebox_supermatter]
map_files = ["icebox_supermatter.dmm"]
directory = "_maps/skyrat/automapper/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [114, 65, 3]
trait_name = "Station"

# Icecats Camp Lower Level
[templates.icebox_icecats_lower]
map_files = ["icemoon_underground_icewalker_lower.dmm"]
directory = "_maps/RandomRuins/IceRuins/skyrat/"
required_map = "IceBoxStation.dmm"
coordinates = [202, 16, 1]
trait_name = "Station"

# Icecats Camp Upper Level
[templates.icebox_icecats_upper]
map_files = ["icemoon_underground_icewalker_upper.dmm"]
directory = "_maps/RandomRuins/IceRuins/skyrat/"
required_map = "IceBoxStation.dmm"
coordinates = [202, 16, 2]
trait_name = "Station"

# Lavaland NE Ashwalker Nest
[templates.lavaland_ashwalker_nenest]
map_files = ["lavaland_ashwalker_nenest.dmm"]
directory = "_maps/skyrat/automapper/templates/mining/"
required_map = "Lavaland.dmm"
coordinates = [223, 224, 1]
trait_name = "Mining"
